name       : gstreamer-editing-services
version    : 1.14.3
release    : 11
source     :
    - https://gstreamer.freedesktop.org/src/gst-editing-services/gstreamer-editing-services-1.14.3.tar.xz : bdb6be75acfaaac3528d30ad47e77eb443d6c55ddabd597c154cd9e88c9a37de
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)  # check
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libxml-2.0)
    - gstreamer-1.0-plugins-good            # check
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer ${version} Solus" \
               --with-package-origin=https://solus-project.com
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check -j1
