name       : gstreamer-editing-services
version    : 1.12.4
release    : 7
source     :
    - https://gstreamer.freedesktop.org/src/gst-editing-services/gstreamer-editing-services-1.12.4.tar.xz : bd7eaa2c9572db9e7e535064024b6f69250de864fe8a5d5be86fa8c7edacca0c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)  # check
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libxml-2.0)
    - gstreamer-1.0-plugins-good            # check
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer ${version} Solus" \
               --with-package-origin=https://solus-project.com
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
