name       : gstreamer-editing-services
version    : 1.18.1
release    : 17
source     :
    - https://gstreamer.freedesktop.org/src/gst-editing-services/gst-editing-services-1.18.1.tar.xz : e93cb3f1896565c57defa72758e49b6eb6685e0f804abd184f395c94822a3927
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(pygobject-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
