name       : gstreamer-editing-services
version    : 1.18.4
release    : 19
source     :
    - https://gitlab.freedesktop.org/gstreamer/gst-editing-services/-/archive/1.18.4/gst-editing-services-1.18.4.tar.gz : 0083990579ab3c77ead401eae44f96de52df49e728e0df1b47a7495f0c98cb36
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(pygobject-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
