name       : gstreamer-editing-services
version    : 1.22.5
release    : 26
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-editing-services/gst-editing-services-1.22.5.tar.xz : bccdd3bd61d86829b16ce0e206db61b33f794ac1792423f9e7cc65d75d1a31b5
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(pygobject-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
