name       : gstreamer-editing-services
version    : 1.18.5
release    : 23
source     :
    - https://gitlab.freedesktop.org/gstreamer/gst-editing-services/-/archive/1.18.5/gst-editing-services-1.18.5.tar.gz : 640004dc7903ecb6f97e4f41d57a6f773c950534bc6ce693f1a7a81d0eb6527d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(pygobject-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
