name       : gstreamer-editing-services
version    : 1.16.0
release    : 13
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-editing-services/gstreamer-editing-services-1.16.0.tar.xz : 82a3faefb2b0d91e134fd02cddeee718b7846a07cbf0127fed7aa03e25495ad1
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)  # check
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(pygobject-3.0)
    - gstreamer-1.0-plugins-good            # check
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
