name       : gstreamer-editing-services
version    : 1.8.2
release    : 5
source     :
    - https://gstreamer.freedesktop.org/src/gst-editing-services/gstreamer-editing-services-1.8.2.tar.xz : a1d57ff9461407cca1f6e7a9f31a5bdb73f73f33c488a3e3318b27e10a4332ae
license    : LGPL-2.0
summary    : Library for creating audio/video editors
description: |
    Library for creating audio/video editors
builddeps  :
    - pkgconfig(gio-2.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libxml-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
